# data cleaning (Basics)

In [1]:
import pandas as pd

In [2]:
df  = pd.read_csv('day1_data.csv')
df

      Name   Age   Salary Department
0     John  25.0  50000.0         IT
1      NaN  30.0  60000.0         HR
2    Alice  21.0 -45000.0    Finance
3      Bob  28.0      NaN         IT
4      Eve   NaN  55000.0         HR
5  Charlie  35.0  65000.0    Finance
6    Alice  31.0  30000.0         IT

In [ ]:
# defining functions for data cleaning
def load_data(file_path):
    return pd.read_csv(file_path)

In [4]:
def convert_numeric(df, cols):
    for col in cols:
        df[col] = pd.to_numeric(df[col], errors = 'coerce')
    return df

In [5]:
def fill_missing(df):
    for col in df.columns:
        if df[col].dtype in ['float64' , 'int64']:
            df[col] = df[col].fillna(df[col].mean())
        else:
            df[col] = df[col].fillna(df[col].mode()[0])
    return df

In [6]:
def remove_invalid_salary(df):
    return df[df['Salary'] >= 0]

In [7]:
def save_result(df, file_path):
    df.to_csv(file_path, index = False)

In [8]:
df = (
    load_data('day1_data.csv')
    .pipe(convert_numeric, ['Age', 'Salary'])
    .pipe(fill_missing)
    .pipe(remove_invalid_salary)
)

In [11]:
save_result(df, 'Cleaned_day1_data.csv')

In [12]:
df

      Name        Age        Salary Department
0     John  25.000000  50000.000000         IT
1    Alice  30.000000  60000.000000         HR
3      Bob  28.000000  35833.333333         IT
4      Eve  28.333333  55000.000000         HR
5  Charlie  35.000000  65000.000000    Finance
6    Alice  31.000000  30000.000000         IT

In [13]:
df.reset_index(drop = True, inplace = True)
df

      Name        Age        Salary Department
0     John  25.000000  50000.000000         IT
1    Alice  30.000000  60000.000000         HR
2      Bob  28.000000  35833.333333         IT
3      Eve  28.333333  55000.000000         HR
4  Charlie  35.000000  65000.000000    Finance
5    Alice  31.000000  30000.000000         IT