# Data Cleaning

In [5]:
import pandas as pd

In [ ]:
df = pd.read_csv('sample_dirty_dataset.csv')
df

      Name   Age  Gender   Salary Department
0    Alice  25.0       F  50000.0         HR
1      Bob   NaN       M  60000.0         IT
2  Charlie  30.0       M      NaN    Finance
3    David  22.0       M  45000.0         IT
4      Eve  29.0       F  70000.0         HR
5    Frank  40.0    Male  80000.0        NaN
6    Grace   NaN  Female  75000.0    Finance
7    Alice  25.0       F  50000.0         HR

In [13]:
# remove outliers
def remove_outliers_IQR(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    return data[(data[column] >= lower_bound) & (data[column] <= upper_bound)]


df_clean = (
    df
    .pipe(remove_outliers_IQR, column = 'Age')
    .pipe(remove_outliers_IQR, column = 'Salary')
)

df_clean
# The error is that the column 'Salary' contains NaN values, which can affect the IQR calculation.
# To fix this, you should drop rows with NaN in the columns before applying the outlier removal.

# Example fix:
df_clean = (
    df.dropna(subset=['Age', 'Salary'])
      .pipe(remove_outliers_IQR, column='Age')
      .pipe(remove_outliers_IQR, column='Salary')
)

df_clean

    Name   Age Gender   Salary Department
0  Alice  25.0      F  50000.0         HR
3  David  22.0      M  45000.0         IT
4    Eve  29.0      F  70000.0         HR
5  Frank  40.0   Male  80000.0    Unknown

In [14]:
df_clean['Department'].fillna('Unknown', inplace  = True)

df_clean.drop_duplicates(inplace = True)

df_clean

    Name   Age Gender   Salary Department
0  Alice  25.0      F  50000.0         HR
3  David  22.0      M  45000.0         IT
4    Eve  29.0      F  70000.0         HR
5  Frank  40.0   Male  80000.0    Unknown

In [15]:
# Making the data consistent
df_clean['Gender'] = df_clean['Gender'].replace({'Male': 'M',
                                                 'Female': 'F'})
df_clean

    Name   Age Gender   Salary Department
0  Alice  25.0      F  50000.0         HR
3  David  22.0      M  45000.0         IT
4    Eve  29.0      F  70000.0         HR
5  Frank  40.0      M  80000.0    Unknown

In [16]:
df_clean.to_csv('Cleaned_data.csv', index = False)