In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('sample_dirty_dataset.csv')
df

      Name   Age  Gender   Salary Department
0    Alice  25.0       F  50000.0         HR
1      Bob   NaN       M  60000.0         IT
2  Charlie  30.0       M      NaN    Finance
3    David  22.0       M  45000.0         IT
4      Eve  29.0       F  70000.0         HR
5    Frank  40.0    Male  80000.0        NaN
6    Grace   NaN  Female  75000.0    Finance
7    Alice  25.0       F  50000.0         HR

In [6]:
df['Age'].fillna(df['Age'].median(), inplace = True)

df['Salary'].fillna(df['Salary'].median(), inplace = True)

df['Department'].fillna('Unknown', inplace = True)

df.drop_duplicates(inplace = True)

df

C:\Users\USER\AppData\Local\Temp\ipykernel_8544\2022133185.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(), inplace = True)
C:\Users\USER\AppData\Local\Temp\ipykernel_8544\2022133185.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].median(), inplace = True)

      Name   Age  Gender   Salary Department
0    Alice  25.0       F  50000.0         HR
1      Bob  27.0       M  60000.0         IT
2  Charlie  30.0       M  60000.0    Finance
3    David  22.0       M  45000.0         IT
4      Eve  29.0       F  70000.0         HR
5    Frank  40.0    Male  80000.0    Unknown
6    Grace  27.0  Female  75000.0    Finance