In [1]:
import pandas as pd

In [2]:
data = {
"A": [10 , 20, 30, 40] ,
"B": [5, 15, 25, 35] ,
"C": [2, 4, 6, 8]
}
df = pd.DataFrame(data)
df

    A   B  C
0  10   5  2
1  20  15  4
2  30  25  6
3  40  35  8

Basic arithemetic operations

In [3]:
df['A  +  B'] = df['A'] + df['B']
df['A - B'] = df['A'] - df['B']
df['A * B'] = df['A'] * df['B']
df['A / B'] = df['A'] / df['B']
df

    A   B  C  A  +  B  A - B  A * B     A / B
0  10   5  2       15      5     50  2.000000
1  20  15  4       35      5    300  1.333333
2  30  25  6       55      5    750  1.200000
3  40  35  8       75      5   1400  1.142857

Statistics

In [4]:
df.mean()
df.median()
df.std()
df.max()
df.min()

A          10.000000
B           5.000000
C           2.000000
A  +  B    15.000000
A - B       5.000000
A * B      50.000000
A / B       1.142857
dtype: float64

In [5]:
df.mean()

A           25.000000
B           20.000000
C            5.000000
A  +  B     45.000000
A - B        5.000000
A * B      625.000000
A / B        1.419048
dtype: float64

In [6]:
df.median()

A           25.000000
B           20.000000
C            5.000000
A  +  B     45.000000
A - B        5.000000
A * B      525.000000
A / B        1.266667
dtype: float64

In [7]:
df.std()

A           12.909944
B           12.909944
C            2.581989
A  +  B     25.819889
A - B        0.000000
A * B      592.311855
A / B        0.395439
dtype: float64

In [8]:
df.max()

A            40.0
B            35.0
C             8.0
A  +  B      75.0
A - B         5.0
A * B      1400.0
A / B         2.0
dtype: float64

In [9]:
df.min()

A          10.000000
B           5.000000
C           2.000000
A  +  B    15.000000
A - B       5.000000
A * B      50.000000
A / B       1.142857
dtype: float64

Element wise operation

In [10]:
import numpy as np

df['sq_c'] = np.sqrt(df['C'])
df['log_A'] = np.log(df['A'])
df['exp_B'] = np.exp(df['B'])
df

,A,B,C,A + B,A - B,A * B,A / B,sq_c,log_A,exp_B
0,10,5,2,15,5,50,2.000000,1.414214,2.302585,1.484132e+02
1,20,15,4,35,5,300,1.333333,2.000000,2.995732,3.269017e+06
2,30,25,6,55,5,750,1.200000,2.449490,3.401197,7.200490e+10
3,40,35,8,75,5,1400,1.142857,2.828427,3.688879,1.586013e+15

Apply

In [11]:
# apply
def square(x):
    return x ** 2

df['Square_A'] = df['A'].apply(square)
df

,A,B,C,A + B,A - B,A * B,A / B,sq_c,log_A,exp_B,Square_A
0,10,5,2,15,5,50,2.000000,1.414214,2.302585,1.484132e+02,100
1,20,15,4,35,5,300,1.333333,2.000000,2.995732,3.269017e+06,400
2,30,25,6,55,5,750,1.200000,2.449490,3.401197,7.200490e+10,900
3,40,35,8,75,5,1400,1.142857,2.828427,3.688879,1.586013e+15,1600

# column wise and row wise operation

In [12]:
# Sum across columns (row - wise )
df[" row_sum "] = df.sum ( axis =1)

# Sum across rows (column - wise )
col_sum = df.sum ( axis =0)
df

,A,B,C,A + B,A - B,A * B,A / B,sq_c,log_A,exp_B,Square_A,row_sum
0,10,5,2,15,5,50,2.000000,1.414214,2.302585,1.484132e+02,100,3.411300e+02
1,20,15,4,35,5,300,1.333333,2.000000,2.995732,3.269017e+06,400,3.269803e+06
2,30,25,6,55,5,750,1.200000,2.449490,3.401197,7.200490e+10,900,7.200490e+10
3,40,35,8,75,5,1400,1.142857,2.828427,3.688879,1.586013e+15,1600,1.586013e+15

In [13]:
col_sum

A            1.000000e+02
B            8.000000e+01
C            2.000000e+01
A  +  B      1.800000e+02
A - B        2.000000e+01
A * B        2.500000e+03
A / B        5.676190e+00
sq_c         8.692130e+00
log_A        1.238839e+01
exp_B        1.586085e+15
Square_A     3.000000e+03
 row_sum     1.586085e+15
dtype: float64